# Generated by Django 3.2.2 on 2021-05-11 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('progress', models.CharField(max_length=30)),
                ('learning_time', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SubSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('progress', models.CharField(max_length=30)),
                ('learning_time', models.CharField(max_length=30)),
                ('text', models.TextField(default=' ')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skill_builder.skill')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('assessment', models.CharField(max_length=30)),
                ('text', models.TextField()),
                ('subSkill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skill_builder.subskill')),
            ],
        ),
    ]
